services:
  inventory:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8110:80"
    volumes:
      - ./inventory:/usr/share/nginx/html:ro
      - ./inventory.conf:/etc/nginx/conf.d/default.conf:ro

  status:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8120:80"
    volumes:
      - ./status:/usr/share/nginx/html:ro
      - ./status.conf:/etc/nginx/conf.d/default.conf:ro

  admin:
    image: nginx:alpine
    ports:
      - "127.0.0.1:8130:80"
    volumes:
      - ./admin:/usr/share/nginx/html:ro
      - ./admin.conf:/etc/nginx/conf.d/default.conf:ro
