server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    add_header X-CyberLabs-Training "beginner-ctf" always;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /robots.txt {
        default_type text/plain;
    }

    location = /training-admin {
        return 403;
    }
}
