services:
  jump:
    build: ./jump
    ports:
      - "127.0.0.1:8822:22"
    networks:
      dmz:
        ipv4_address: 172.28.27.10
      internal:
        ipv4_address: 172.28.28.10

  api:
    image: nginx:alpine
    networks:
      internal:
        ipv4_address: 172.28.28.11
    volumes:
      - ./api:/usr/share/nginx/html:ro

  admin:
    image: nginx:alpine
    networks:
      internal:
        ipv4_address: 172.28.28.12
    volumes:
      - ./admin:/usr/share/nginx/html:ro

networks:
  dmz:
    ipam:
      config:
        - subnet: 172.28.27.0/28
  internal:
    internal: true
    ipam:
      config:
        - subnet: 172.28.28.0/28
