services:
  app:
    build: .
    env_file:
      - ./runtime/web.env
    environment:
      LOG_PATH: /logs/access.jsonl
    ports:
      - "127.0.0.1:8500:5000"
    volumes:
      - ./runtime:/logs
