server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    add_header X-CyberLabs-Level "extra-practice" always;
    add_header X-CyberLabs-Lab "network-service-triage" always;
    add_header X-CyberLabs-Service "asset-inventory" always;

    location / {
        try_files $uri $uri/ =404;
    }
}
